### ISSUE TITLE
Date popup Not displayed

### ISSUE THREAD

**Issue by matus-vacula** [ReDI-School/F24-Berlin-Web-Circle#247]
![Image](https://github.com/user-attachments/assets/887f12ac-0aae-4d6b-a82a-88245ab9fa4c)
Date popup should correctly lode with it functionality

**Comment by grabinskij** [comment]
While I was working on added calendar feature #72 I accidentally met acceptance criteria of this ticket. As soon as the #72 is approved, this ticket will be closed automatically.

**Comment by grabinskij** [comment]
Since the newest PR Feature/embed calendar in reservation https://github.com/ReDI-School/F24-Berlin-Web-Circle/pull/259 with the newest changes was approved and merged to the main branch it is not need to approve or merge this PR. So, I close Date popup Not displayed [#247](https://github.com/ReDI-School/F24-Berlin-Web-Circle/issues/247) ticket.
