### ISSUE TITLE
change website background color

### ISSUE THREAD

**Issue by orYoffe** [ReDI-School/F24-Berlin-Web-Circle#58]
Adjust the background color to match the design https://www.airbnb.com/ 

AC:
- We see the background color matches the design on the website https://www.airbnb.com/

**Comment by grabinskij** [comment]
Hi @orYoffe,

After reviewing the design on [Airbnb](https://www.airbnb.com/), I noticed that the background color is already set to white, which matches what we currently have in the app. Since there’s no need to change the background color, I believe the task is already complete as-is.

I suggest we close this issue without making any further changes. Please let me know if you agree.

Thanks!
Bohdan
